//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionCompanyApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class СтройКомпанияEntities : DbContext
    {
        public СтройКомпанияEntities()
            : base("name=СтройКомпанияEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<construction_stages> construction_stages { get; set; }
        public virtual DbSet<customers> customers { get; set; }
        public virtual DbSet<employees> employees { get; set; }
        public virtual DbSet<house_types> house_types { get; set; }
        public virtual DbSet<materials> materials { get; set; }
        public virtual DbSet<order_materials> order_materials { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<projects> projects { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
