//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionCompanyApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orders()
        {
            this.construction_stages = new HashSet<construction_stages>();
            this.order_materials = new HashSet<order_materials>();
        }
    
        public int order_id { get; set; }
        public int customer_id { get; set; }
        public int project_id { get; set; }
        public int foreman_id { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date_planned { get; set; }
        public Nullable<System.DateTime> end_date_actual { get; set; }
        public decimal total_cost { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> final_cost { get; set; }
        public string status { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<construction_stages> construction_stages { get; set; }
        public virtual customers customers { get; set; }
        public virtual employees employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_materials> order_materials { get; set; }
        public virtual projects projects { get; set; }
    }
}
