//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionCompanyApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class projects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public projects()
        {
            this.orders = new HashSet<orders>();
        }
    
        public int project_id { get; set; }
        public string project_name { get; set; }
        public int type_id { get; set; }
        public decimal total_area { get; set; }
        public int floors { get; set; }
        public int bedrooms { get; set; }
        public decimal price_per_m2 { get; set; }
        public int construction_time_months { get; set; }
        public Nullable<bool> is_active { get; set; }
    
        public virtual house_types house_types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orders> orders { get; set; }
    }
}
